from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET
from decouple import Config, RepositoryEnv
from pathlib import Path


# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

#Close all open positions and orders
ABORT_ALL_POSITIONS = True

#Find cointegrated pairs
FIND_COINTEGRATED = True

#Place Trades
PLACE_TRADES = True

#Resolution
RESOLUTION = "1HOUR"

#Stats Window
WINDOW = 21
#Calculate rolling moving average based on 21 days

#Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1,5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

#Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

#Ethereum Address
ETHEREUM_ADDRESS = "0xd60f598d6727D4e268B190e5Be4e53BA3e9E9256"

BASE_DIR = Path(__file__).parent.parent  

# Construct path to .env file
env_path = BASE_DIR / ".env"

# Load config from .env file
config = Config(RepositoryEnv(env_path)) 
ETHEREUM_ADDRESS = "0xd60f598d6727D4e268B190e5Be4e53BA3e9E9256"


# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
# Must be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET =config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET


#HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_SEPOLIA

#HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/vyrnaB-4Dw-sCqRkGENWEUuPBQNB46No"
HTTP_PROVIDER_TESTNET = "https://eth-sepolia.g.alchemy.com/v2/oAWmf3yhxOeoLuEpR7pZyU-85rxlOMdH"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET

